//// 
//// Autogenerated by xlw 
//// Do not edit this file, it will be overwritten 
//// by InterfaceGenerator 
////

#include "xlw/MyContainers.h"
#include <xlw/CellMatrix.h>
#include "q_StandardBlackScholes.h"
#include <xlw/xlw.h>
#include <xlw/XlFunctionRegistration.h>
#include <stdexcept>
#include <xlw/XlOpenClose.h>
#include <xlw/HiResTimer.h>
using namespace xlw;

namespace {
const char* LibraryName = "QuantLab";
};


// registrations start here


namespace
{
XLRegistration::Arg
q_StandarBlackScholesArgs[]=
{
{ "spot"," spot ","B"},
{ "strike"," strike ","B"},
{ "interestRate","  Interest Rate ","B"},
{ "valueDate","  Value date ","B"},
{ "expiryDtae"," Expiry ","B"},
{ "volatility"," Volatility ","B"},
{ "Dividends"," Dividends ","B"},
{ "isCall"," true for Call, false for Put ","XLF_OPER"}
};
  XLRegistration::XLFunctionRegistrationHelper
registerq_StandarBlackScholes("xlq_StandarBlackScholes",
"q_StandarBlackScholes",
" Call and Put price with standar log-normal Black-Scholes model ",
LibraryName,
q_StandarBlackScholesArgs,
8
,false
,false
,""
,""
,false
,false
,false
);
}



extern "C"
{
LPXLFOPER EXCEL_EXPORT
xlq_StandarBlackScholes(
double spot,
double strike,
double interestRate,
double valueDate,
double expiryDtae,
double volatility,
double Dividends,
LPXLFOPER isCalla)
{
EXCEL_BEGIN;

	if (XlfExcel::Instance().IsCalledByFuncWiz())
		return XlfOper(true);








XlfOper isCallb(
	(isCalla));
bool isCall(
	isCallb.AsBool("isCall"));

double result(
	q_StandarBlackScholes(
		spot,
		strike,
		interestRate,
		valueDate,
		expiryDtae,
		volatility,
		Dividends,
		isCall)
	);
return XlfOper(result);
EXCEL_END
}
}



//////////////////////////

//////////////////////////
// Methods that will get registered to execute in AutoOpen
//////////////////////////

//////////////////////////
// Methods that will get registered to execute in AutoClose
//////////////////////////

